# Day 10

# Numpy

In [5]:
import numpy as np

# Arithmetic opr
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

a1 + a2
a1 - a2
a1 * a2
a1 // a2
a1 ** a2


array([      1,     128,    6561,  262144, 9765625])

In [6]:
# broadcasting
a1 +10

array([11, 12, 13, 14, 15])

In [17]:
# Deep and Shallow copy

# shallow copy
a1
slice = a1[:3]
slice = slice * 10
slice
a1
b1 = a1.copy()# makes shallow copy of it
# so there is no change in original array but if we do in list they changed.

# deep copy
b1 = a1
b1[0]=99
a1

array([99,  2,  3,  4,  5])

In [18]:
# Matrix opr
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])

m1

array([[1, 2],
       [3, 4]])

In [19]:
m2

array([[5, 6],
       [7, 8]])

In [22]:
# multiplication
m1 @ m2
np.dot(m1,m2)

array([[19, 22],
       [43, 50]])

In [23]:
# transpose
m1.T


array([[1, 3],
       [2, 4]])

In [26]:
# Advance Array Manipulation

# Stacking of array
#you can't stack two matrix

np.vstack((a1,a2)) # vertical stack
np.hstack((a1,a2)) # horizontal stack
np.column_stack((a1,a2)) # column stack



array([[99,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [28]:
# splitting arrays
c1 = np.arange(16).reshape(4,4)
c1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c1,2) # horizontal split
np.vsplit(c1,2) # vertical split

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]