# Day 11

# Numpy

In [13]:
# Valid Sudoku
import numpy as np
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

b = np.sum(s,axis=1)
b==45
s1 = s[0:3,0:3]
np.sum(s1,axis=0)
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())




45
45
45
45
45
45
45
45
45


In [2]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [14]:
# Get the shape of the matrix.
data.shape

(5, 3)

In [16]:
# find avg age of std.
np.mean(data[:,0],axis=0)

np.float64(18.4)

In [17]:
# Extract Math marks of all students
data[:,1]


array([85, 92, 76, 65, 90])

In [18]:
# Find the highest Science mark.
data[:,2].max()

np.int64(95)

In [21]:
# Get details of the std who scored more than 90 in math
data[data[:,1]>90]
data


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [23]:
# Increase Math marks of all std by 5
data[:,1]+5
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [26]:
# find how many std are younger than 19
len(data[data[:,0]<19])

3

In [28]:
# Calculate the avg marks in each sub(column-wise mean)
np.mean(data[:,1:],axis=0)


array([81.6, 83.2])

In [32]:
# get data of std who scored at least 80 in both sub

data[data[:,1]>=80] & (data[data[:,2]>=80])

array([[18, 84, 72],
       [17, 76, 88],
       [20, 90, 85]])

In [33]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [39]:
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [2]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

# Replace all science marks < 75 with 0
data[:,2][data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])