# Day 8

# Numpy

In [2]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
#numpy was made in 2005 by merging numeric and Numarray by Travis Oliphant.
# numpy is written in C which are compiled and super fast.
#This is the main reason numPy is up to 50PX faster than python list.


In [ ]:
# Numpy Arrays
# - [1,2,3,4] - array and list but what diff.

# list - datatype - mixed , performance - slower, Memory Efficiency - Low, Vector operations - Manual loops.

# Numpy array - datatype - Same datatype only, performance - Faster(c-level), Memory Efficiency - High, vector operations - Easy Fast.

import numpy as np

# Basic Array creation
arr = np.array([1,2,3,4])
print(arr)

a = [1,2,3,4,5,'hello']

print(np.array(a))
# it will shows as array(['1' '2' '3' '4' '5' 'hello'], dtype='<U32')


# Vectors
# single dimensional

# Matrix
# 2dimensional

# tensor
# more than 2d

l = [[1,2,3,5],[6,7,8,9],[10,11,12,13]]
print(l)

print(np.array(l))


[1 2 3 4]
['1' '2' '3' '4' '5' 'hello']
[[1, 2, 3, 5], [6, 7, 8, 9], [10, 11, 12, 13]]
[[ 1  2  3  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [25]:
# array generation fn
# import numpy as np

#arange()
arr = np.arange(1,22)
print(arr)


arr2 = np.arange(1,20,2)
print(arr2)

#zeros()

arr3 = np.zeros(6)
print(arr3)
arr4 = np.zeros((6,6))
#.zeros((rows,column))
print(arr4)

# ones()

arr5 = np.ones((4,8))
print(arr5)

# linspace
arr6 = np.linspace(1,5,3) # means linear space
print(arr6)

print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
[ 1  3  5  7  9 11 13 15 17 19]
[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[1. 3. 5.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


In [23]:
# Random Generation fn

# rand (normalization)
arr = np.random.rand(5)
print(arr)

# randn (standardization)
arr2 = np.random.randn(10)
print(arr2)

# randint
arr3 = np.random.randint(10,20,10)
print(arr3)

[0.11527135 0.91415582 0.49269098 0.40027773 0.75019732]
[ 0.76408533  1.22607229 -0.70920951 -0.86327621  1.97239103  0.40675528
  0.67621928 -1.03891986  0.6190115   1.196995  ]
[17 19 17 10 18 19 11 19 19 19]


In [28]:
# array attributes

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

# shape
arr.shape

# size 
arr.size

# dtype
arr.dtype


[[1 2 3]
 [4 5 6]]


dtype('int64')

In [31]:
# Array Methods

# min
arr.min()

#max
arr.max()

#sum
arr.sum()



np.int64(21)