# Day 9

# Numpy

In [6]:
import numpy as np
arr = np.arange(11,21)
arr 





array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
# indexing
arr[6]

np.int64(17)

In [10]:
#Slicing
arr[0:3]

array([11, 12, 13])

In [13]:
# indexing and slicing in matrix

arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [16]:
#indexing
arr[0,0]
# arr[rows,column]

np.int64(1)

In [17]:
# Slicing
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [18]:
# Boolean Indexing

arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
bool_inde = arr%2==0
bool_inde

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [20]:
arr = arr[bool_inde]
arr

array([12, 14, 16, 18, 20])